/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekku;

import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class Barang extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    public Barang() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelutama = new javax.swing.JPanel();
        Pilihan = new javax.swing.JPanel();
        JBKipas = new javax.swing.JButton();
        JBLaptop = new javax.swing.JButton();
        JBTv = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Barang = new javax.swing.JPanel();
        KIPAS = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        KipasUap = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JIUap = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        JCUap = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        JTUap = new javax.swing.JTextField();
        Uapbeli = new javax.swing.JButton();
        KipasKrisbow = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        JKriss = new javax.swing.JLabel();
        JIKriss = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Krissbeli = new javax.swing.JButton();
        JCKriss = new javax.swing.JCheckBox();
        JTKriss = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        LAPTOP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Acer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JIAcer = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        JCAcer = new javax.swing.JCheckBox();
        JTAcer = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Acerbeli = new javax.swing.JButton();
        LENOVO = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JILenovo = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        JCLenovo = new javax.swing.JCheckBox();
        JTLenovo = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Lenovobeli = new javax.swing.JButton();
        TV = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Samsung = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JISamsung = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        JCSamsung = new javax.swing.JCheckBox();
        JTSamsung = new javax.swing.JTextField();
        Samsungbeli = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        Polytron = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JIPolytron = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        JCPolytron = new javax.swing.JCheckBox();
        JTPolytron = new javax.swing.JTextField();
        Polytronbeli = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panelutama.setBackground(new java.awt.Color(41, 128, 185));

        Pilihan.setBackground(new java.awt.Color(130, 204, 221));
        Pilihan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        JBKipas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBKipas.setText("KIPAS");
        JBKipas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBKipasActionPerformed(evt);
            }
        });

        JBLaptop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBLaptop.setText("LAPTOP");
        JBLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBLaptopActionPerformed(evt);
            }
        });

        JBTv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBTv.setText("TV");
        JBTv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTvActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel1.setText("PILIH ITEM:");
        jLabel1.setMaximumSize(new java.awt.Dimension(550, 512));
        jLabel1.setMinimumSize(new java.awt.Dimension(550, 512));

        jButton1.setBackground(new java.awt.Color(244, 67, 54));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PilihanLayout = new javax.swing.GroupLayout(Pilihan);
        Pilihan.setLayout(PilihanLayout);
        PilihanLayout.setHorizontalGroup(
            PilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilihanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBKipas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBLaptop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBTv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PilihanLayout.createSequentialGroup()
                        .addGroup(PilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PilihanLayout.setVerticalGroup(
            PilihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PilihanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(JBKipas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(JBLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(JBTv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        Barang.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        Barang.setLayout(new java.awt.CardLayout());

        KIPAS.setBackground(new java.awt.Color(9, 132, 227));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("KIPAS");

        KipasUap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\10335728_1 (1).jpg")); // NOI18N

        jLabel8.setText("Kipas Angin Uap Kris  75W");

        JIUap.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-info-48.png")); // NOI18N
        JIUap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JIUapActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel18.setText("Rp. 900.000,00");

        JCUap.setText("Pesan");
        JCUap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCUapActionPerformed(evt);
            }
        });

        jLabel25.setText("Jumlah:");

        JTUap.setEditable(false);
        JTUap.setEnabled(false);
        JTUap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTUapActionPerformed(evt);
            }
        });

        Uapbeli.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-add-shopping-cart-32.png")); // NOI18N
        Uapbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UapbeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KipasUapLayout = new javax.swing.GroupLayout(KipasUap);
        KipasUap.setLayout(KipasUapLayout);
        KipasUapLayout.setHorizontalGroup(
            KipasUapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KipasUapLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(KipasUapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KipasUapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KipasUapLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KipasUapLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(39, 39, 39)))
                    .addGroup(KipasUapLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)))
                .addGroup(KipasUapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JIUap, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JCUap)
                    .addComponent(Uapbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KipasUapLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(KipasUapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(KipasUapLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(JTUap, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        KipasUapLayout.setVerticalGroup(
            KipasUapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KipasUapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KipasUapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KipasUapLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(KipasUapLayout.createSequentialGroup()
                        .addComponent(JIUap, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JCUap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTUap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Uapbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
        );

        KipasKrisbow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\Webp.net-resizeimage (1).png")); // NOI18N

        JKriss.setText("Kipas Angin Krisbow 80W");

        JIKriss.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-info-48.png")); // NOI18N
        JIKriss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JIKrissActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel17.setText("Rp. 370.000,00");

        Krissbeli.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-add-shopping-cart-32.png")); // NOI18N
        Krissbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KrissbeliActionPerformed(evt);
            }
        });

        JCKriss.setText("Pesan");
        JCKriss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCKrissActionPerformed(evt);
            }
        });

        JTKriss.setEditable(false);
        JTKriss.setEnabled(false);
        JTKriss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTKrissActionPerformed(evt);
            }
        });

        jLabel24.setText("Jumlah:");

        javax.swing.GroupLayout KipasKrisbowLayout = new javax.swing.GroupLayout(KipasKrisbow);
        KipasKrisbow.setLayout(KipasKrisbowLayout);
        KipasKrisbowLayout.setHorizontalGroup(
            KipasKrisbowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KipasKrisbowLayout.createSequentialGroup()
                .addGroup(KipasKrisbowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KipasKrisbowLayout.createSequentialGroup()
                        .addContainerGap(60, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(37, 37, 37)
                        .addComponent(JIKriss, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KipasKrisbowLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(KipasKrisbowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JKriss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(KipasKrisbowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KipasKrisbowLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(KipasKrisbowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JCKriss)
                                    .addComponent(Krissbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(KipasKrisbowLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(KipasKrisbowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addGroup(KipasKrisbowLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(JTKriss, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        KipasKrisbowLayout.setVerticalGroup(
            KipasKrisbowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KipasKrisbowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KipasKrisbowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KipasKrisbowLayout.createSequentialGroup()
                        .addComponent(JIKriss, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(JCKriss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTKriss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGroup(KipasKrisbowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KipasKrisbowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(JKriss, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(KipasKrisbowLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Krissbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout KIPASLayout = new javax.swing.GroupLayout(KIPAS);
        KIPAS.setLayout(KIPASLayout);
        KIPASLayout.setHorizontalGroup(
            KIPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KIPASLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(KIPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KIPASLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(KIPASLayout.createSequentialGroup()
                        .addComponent(KipasKrisbow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KipasUap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        KIPASLayout.setVerticalGroup(
            KIPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KIPASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KIPASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KipasUap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KipasKrisbow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        Barang.add(KIPAS, "card2");

        LAPTOP.setBackground(new java.awt.Color(112, 161, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("LAPTOP");

        Acer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\594ba434150ba0ec6cebf0e0_1515481791.jpg")); // NOI18N

        jLabel10.setText("Acer ASPIRE One Z1402");

        JIAcer.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-info-48.png")); // NOI18N
        JIAcer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JIAcerActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel19.setText("Rp. 3.420.000,00");

        JCAcer.setText("Pesan");
        JCAcer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCAcerActionPerformed(evt);
            }
        });

        JTAcer.setEditable(false);
        JTAcer.setEnabled(false);
        JTAcer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTAcerActionPerformed(evt);
            }
        });

        jLabel26.setText("Jumlah:");

        Acerbeli.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-add-shopping-cart-32.png")); // NOI18N
        Acerbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcerbeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AcerLayout = new javax.swing.GroupLayout(Acer);
        Acer.setLayout(AcerLayout);
        AcerLayout.setHorizontalGroup(
            AcerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AcerLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(AcerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AcerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(AcerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19)))
                .addGroup(AcerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AcerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(JIAcer, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(AcerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(AcerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCAcer)
                            .addComponent(Acerbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AcerLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(AcerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addGroup(AcerLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(JTAcer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        AcerLayout.setVerticalGroup(
            AcerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AcerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AcerLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(AcerLayout.createSequentialGroup()
                        .addComponent(JIAcer, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JCAcer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTAcer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Acerbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        LENOVO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\594ba434150ba0ec6cebf0e0_1520238844.jpg")); // NOI18N

        jLabel12.setText("LENOVO Ideapad 100-15IBD");

        JILenovo.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-info-48.png")); // NOI18N
        JILenovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JILenovoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel20.setText("Rp. 4.900.000,00");

        JCLenovo.setText("Pesan");
        JCLenovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCLenovoActionPerformed(evt);
            }
        });

        JTLenovo.setEditable(false);
        JTLenovo.setEnabled(false);
        JTLenovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTLenovoActionPerformed(evt);
            }
        });

        jLabel27.setText("Jumlah:");

        Lenovobeli.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-add-shopping-cart-32.png")); // NOI18N
        Lenovobeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LenovobeliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LENOVOLayout = new javax.swing.GroupLayout(LENOVO);
        LENOVO.setLayout(LENOVOLayout);
        LENOVOLayout.setHorizontalGroup(
            LENOVOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LENOVOLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(LENOVOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LENOVOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LENOVOLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20)))
                .addGroup(LENOVOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LENOVOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(JILenovo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(LENOVOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(LENOVOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCLenovo)
                            .addComponent(Lenovobeli, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LENOVOLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(LENOVOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addGroup(LENOVOLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(JTLenovo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        LENOVOLayout.setVerticalGroup(
            LENOVOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LENOVOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LENOVOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LENOVOLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LENOVOLayout.createSequentialGroup()
                        .addComponent(JILenovo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JCLenovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTLenovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lenovobeli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LAPTOPLayout = new javax.swing.GroupLayout(LAPTOP);
        LAPTOP.setLayout(LAPTOPLayout);
        LAPTOPLayout.setHorizontalGroup(
            LAPTOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAPTOPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LAPTOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(LAPTOPLayout.createSequentialGroup()
                        .addComponent(Acer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LENOVO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        LAPTOPLayout.setVerticalGroup(
            LAPTOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LAPTOPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(LAPTOPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LENOVO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Acer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        Barang.add(LAPTOP, "card3");

        TV.setBackground(new java.awt.Color(83, 82, 237));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TELEVISI");

        Samsung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\Review dan Harga TV LED Samsung UA24H4150 24 Inch HD Ready.JPG")); // NOI18N

        jLabel14.setText("TV LED Samsung U24H4150");

        JISamsung.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-info-48.png")); // NOI18N
        JISamsung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JISamsungActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel23.setText("Rp. 1.850.000,00");

        JCSamsung.setText("Pesan");
        JCSamsung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCSamsungActionPerformed(evt);
            }
        });

        JTSamsung.setEditable(false);
        JTSamsung.setEnabled(false);
        JTSamsung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTSamsungActionPerformed(evt);
            }
        });

        Samsungbeli.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-add-shopping-cart-32.png")); // NOI18N
        Samsungbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SamsungbeliActionPerformed(evt);
            }
        });

        jLabel29.setText("Jumlah:");

        javax.swing.GroupLayout SamsungLayout = new javax.swing.GroupLayout(Samsung);
        Samsung.setLayout(SamsungLayout);
        SamsungLayout.setHorizontalGroup(
            SamsungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SamsungLayout.createSequentialGroup()
                .addGroup(SamsungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SamsungLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(SamsungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                    .addGroup(SamsungLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel23)))
                .addGroup(SamsungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SamsungLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(JISamsung, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(SamsungLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SamsungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCSamsung)
                            .addComponent(Samsungbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SamsungLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(SamsungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addGroup(SamsungLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(JTSamsung, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        SamsungLayout.setVerticalGroup(
            SamsungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SamsungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SamsungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SamsungLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(SamsungLayout.createSequentialGroup()
                        .addComponent(JISamsung, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JCSamsung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTSamsung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Samsungbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Polytron.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\399a224801050fc7852e7c21f44346fb.jpg")); // NOI18N

        jLabel16.setText("TV LED Polytron PLD60T965");

        JIPolytron.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-info-48.png")); // NOI18N
        JIPolytron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JIPolytronActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel22.setText("Rp. 1.745.000,00");

        JCPolytron.setText("Pesan");
        JCPolytron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCPolytronActionPerformed(evt);
            }
        });

        JTPolytron.setEditable(false);
        JTPolytron.setEnabled(false);
        JTPolytron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTPolytronActionPerformed(evt);
            }
        });

        Polytronbeli.setIcon(new javax.swing.ImageIcon("H:\\tugas analog\\icons8-add-shopping-cart-32.png")); // NOI18N
        Polytronbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolytronbeliActionPerformed(evt);
            }
        });

        jLabel28.setText("Jumlah:");

        javax.swing.GroupLayout PolytronLayout = new javax.swing.GroupLayout(Polytron);
        Polytron.setLayout(PolytronLayout);
        PolytronLayout.setHorizontalGroup(
            PolytronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PolytronLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PolytronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PolytronLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)))
                .addGroup(PolytronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PolytronLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(JIPolytron, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(PolytronLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PolytronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JCPolytron)
                            .addComponent(Polytronbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PolytronLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(PolytronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addGroup(PolytronLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(JTPolytron, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PolytronLayout.setVerticalGroup(
            PolytronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PolytronLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PolytronLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PolytronLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PolytronLayout.createSequentialGroup()
                        .addComponent(JIPolytron, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JCPolytron)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTPolytron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Polytronbeli, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout TVLayout = new javax.swing.GroupLayout(TV);
        TV.setLayout(TVLayout);
        TVLayout.setHorizontalGroup(
            TVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TVLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Polytron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(Samsung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        TVLayout.setVerticalGroup(
            TVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Samsung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Polytron, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        Barang.add(TV, "card4");

        javax.swing.GroupLayout PanelutamaLayout = new javax.swing.GroupLayout(Panelutama);
        Panelutama.setLayout(PanelutamaLayout);
        PanelutamaLayout.setHorizontalGroup(
            PanelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelutamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelutamaLayout.setVerticalGroup(
            PanelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelutamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pilihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBKipasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBKipasActionPerformed
    Barang.removeAll();
    Barang.repaint();
    Barang.revalidate();
    
    //Add
    Barang.add(KIPAS);
    Barang.repaint();
    Barang.revalidate();
    }//GEN-LAST:event_JBKipasActionPerformed

    private void JBLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBLaptopActionPerformed
    Barang.removeAll();
    Barang.repaint();
    Barang.revalidate();
    
    //Add
    Barang.add(LAPTOP);
    Barang.repaint();
    Barang.revalidate();
    }//GEN-LAST:event_JBLaptopActionPerformed

    private void JBTvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTvActionPerformed
    Barang.removeAll();
    Barang.repaint();
    Barang.revalidate();
    
    //Add
    Barang.add(TV);
    Barang.repaint();
    Barang.revalidate();
    }//GEN-LAST:event_JBTvActionPerformed

    private void JIKrissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JIKrissActionPerformed
    Krissinfo n = new Krissinfo();
    n.setVisible(true);
    }//GEN-LAST:event_JIKrissActionPerformed

    private void JIUapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JIUapActionPerformed
    Uapinfo n = new Uapinfo();
    n.setVisible(true);
    }//GEN-LAST:event_JIUapActionPerformed

    private void JIAcerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JIAcerActionPerformed
    Acerinfo n = new Acerinfo();
    n.setVisible(true);
    }//GEN-LAST:event_JIAcerActionPerformed

    private void JILenovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JILenovoActionPerformed
    Lenovoinfo n = new Lenovoinfo();
    n.setVisible(true);
    }//GEN-LAST:event_JILenovoActionPerformed

    private void JISamsungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JISamsungActionPerformed
    Samsunginfo n = new Samsunginfo();
    n.setVisible(true);
    }//GEN-LAST:event_JISamsungActionPerformed

    private void JIPolytronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JIPolytronActionPerformed
    Polytroninfo n = new Polytroninfo();
    n.setVisible(true);
    }//GEN-LAST:event_JIPolytronActionPerformed

    private void KrissbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KrissbeliActionPerformed
     String Barang = "Kipas Angin Krisbow 80W";
     String Banyak =  JTKriss.getText();
     String Harga = "370000";
     Integer hasil = Integer.parseInt(JTKriss.getText()) * 370000;
     
     String Total = String.valueOf(hasil);
     new Beli(Barang,Banyak,Harga,Total).setVisible(true);
     this.setVisible(false);
     
    

    }//GEN-LAST:event_KrissbeliActionPerformed

    private void JCKrissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCKrissActionPerformed
    if(JCKriss.isSelected()){
        JTKriss.setEnabled(true);
        JTKriss.setEditable(true);
    }else{
        JTKriss.setEnabled(false);
        JTKriss.setEditable(false);
        JTKriss.setText("");
    }
    }//GEN-LAST:event_JCKrissActionPerformed

    private void JTKrissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTKrissActionPerformed
    
    }//GEN-LAST:event_JTKrissActionPerformed

    private void JCUapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCUapActionPerformed
    if(JCUap.isSelected()){
        JTUap.setEnabled(true);
        JTUap.setEditable(true);
    }else{
        JTUap.setEnabled(false);
        JTUap.setEditable(false);
        JTUap.setText("");
    }
    }//GEN-LAST:event_JCUapActionPerformed

    private void JTUapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTUapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTUapActionPerformed

    private void UapbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UapbeliActionPerformed
    String Barang = "Kipas Angin Uap Kris  75W";
    String Banyak =  JTUap.getText();
    String Harga = "900000";
    Integer hasil = Integer.parseInt(JTUap.getText()) * 900000;
    String Total = String.valueOf(hasil);
    new Beli(Barang,Banyak,Harga,Total).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_UapbeliActionPerformed

    private void JCAcerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCAcerActionPerformed
    if(JCAcer.isSelected()){
        JTAcer.setEnabled(true);
        JTAcer.setEditable(true);
    }else{
        JTAcer.setEnabled(false);
        JTAcer.setEditable(false);
        JTAcer.setText("");
    }
    }//GEN-LAST:event_JCAcerActionPerformed

    private void JTAcerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTAcerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTAcerActionPerformed

    private void AcerbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcerbeliActionPerformed
    String Barang = "Acer ASPIRE One Z1402";
    String Banyak =  JTAcer.getText();
    String Harga = "3420000";
    Integer hasil = Integer.parseInt(JTAcer.getText()) * 3420000;
    String Total = String.valueOf(hasil);
    new Beli(Barang,Banyak,Harga,Total).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_AcerbeliActionPerformed

    private void JCLenovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCLenovoActionPerformed
    if(JCLenovo.isSelected()){
        JTLenovo.setEnabled(true);
        JTLenovo.setEditable(true);
    }else{
        JTLenovo.setEnabled(false);
        JTLenovo.setEditable(false);
        JTLenovo.setText("");
    }
    }//GEN-LAST:event_JCLenovoActionPerformed

    private void JTLenovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTLenovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTLenovoActionPerformed

    private void LenovobeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LenovobeliActionPerformed
    String Barang = "LENOVO Ideapad 100-15IBD";
    String Banyak =  JTLenovo.getText();
    String Harga = "4900000";
    Integer hasil = Integer.parseInt(JTLenovo.getText()) * 4900000;
    String Total = String.valueOf(hasil);
    new Beli(Barang,Banyak,Harga,Total).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_LenovobeliActionPerformed

    private void JCPolytronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCPolytronActionPerformed
    if(JCPolytron.isSelected()){
        JTPolytron.setEnabled(true);
        JTPolytron.setEditable(true);
    }else{
        JTPolytron.setEnabled(false);
        JTPolytron.setEditable(false);
        JTPolytron.setText("");
    }
    }//GEN-LAST:event_JCPolytronActionPerformed

    private void JTPolytronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTPolytronActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTPolytronActionPerformed

    private void PolytronbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolytronbeliActionPerformed
    String Barang = "TV LED Polytron PLD60T965";
    String Banyak =  JTPolytron.getText();
    String Harga = "1745000";
    Integer hasil = Integer.parseInt(JTPolytron.getText()) * 1745000;
    String Total = String.valueOf(hasil);
    new Beli(Barang,Banyak,Harga,Total).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_PolytronbeliActionPerformed

    private void JCSamsungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCSamsungActionPerformed
    if(JCSamsung.isSelected()){
        JTSamsung.setEnabled(true);
        JTSamsung.setEditable(true);
    }else{
        JTSamsung.setEnabled(false);
        JTSamsung.setEditable(false);
        JTSamsung.setText("");
    }
    }//GEN-LAST:event_JCSamsungActionPerformed

    private void JTSamsungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTSamsungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTSamsungActionPerformed

    private void SamsungbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SamsungbeliActionPerformed
    String Barang = "TV LED Samsung U24H4150";
    String Banyak =  JTSamsung.getText();
    String Harga = "1850000";
    Integer hasil = Integer.parseInt(JTSamsung.getText()) * 1850000;
    String Total = String.valueOf(hasil);
    new Beli(Barang,Banyak,Harga,Total).setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_SamsungbeliActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
    new MenuUtama().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Barang().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acer;
    public javax.swing.JButton Acerbeli;
    private javax.swing.JPanel Barang;
    private javax.swing.JButton JBKipas;
    private javax.swing.JButton JBLaptop;
    private javax.swing.JButton JBTv;
    private javax.swing.JCheckBox JCAcer;
    private javax.swing.JCheckBox JCKriss;
    private javax.swing.JCheckBox JCLenovo;
    private javax.swing.JCheckBox JCPolytron;
    private javax.swing.JCheckBox JCSamsung;
    private javax.swing.JCheckBox JCUap;
    private javax.swing.JButton JIAcer;
    private javax.swing.JButton JIKriss;
    private javax.swing.JButton JILenovo;
    private javax.swing.JButton JIPolytron;
    private javax.swing.JButton JISamsung;
    private javax.swing.JButton JIUap;
    private javax.swing.JLabel JKriss;
    private javax.swing.JTextField JTAcer;
    private javax.swing.JTextField JTKriss;
    private javax.swing.JTextField JTLenovo;
    private javax.swing.JTextField JTPolytron;
    private javax.swing.JTextField JTSamsung;
    private javax.swing.JTextField JTUap;
    private javax.swing.JPanel KIPAS;
    private javax.swing.JPanel KipasKrisbow;
    private javax.swing.JPanel KipasUap;
    public javax.swing.JButton Krissbeli;
    private javax.swing.JPanel LAPTOP;
    private javax.swing.JPanel LENOVO;
    public javax.swing.JButton Lenovobeli;
    private javax.swing.JPanel Panelutama;
    private javax.swing.JPanel Pilihan;
    private javax.swing.JPanel Polytron;
    public javax.swing.JButton Polytronbeli;
    private javax.swing.JPanel Samsung;
    public javax.swing.JButton Samsungbeli;
    private javax.swing.JPanel TV;
    public javax.swing.JButton Uapbeli;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
